// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3RSB_FjUAkd1iRkI1QxBNZdutBTZKsk',
    appId: '1:1065290692027:web:6da8ff8e85e88e0085409e',
    messagingSenderId: '1065290692027',
    projectId: 'noticeboard-aebdd',
    authDomain: 'noticeboard-aebdd.firebaseapp.com',
    storageBucket: 'noticeboard-aebdd.firebasestorage.app',
    measurementId: 'G-6R22N7RRWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAnngpzpyz-oDh9hDef55-Hc2oZmP2JDk',
    appId: '1:1065290692027:android:ca5a175d37f0c6e985409e',
    messagingSenderId: '1065290692027',
    projectId: 'noticeboard-aebdd',
    storageBucket: 'noticeboard-aebdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKinsFG2n9tvuhL9MEsICXLXqSfnlJC8',
    appId: '1:1065290692027:ios:384cb508cbc5995e85409e',
    messagingSenderId: '1065290692027',
    projectId: 'noticeboard-aebdd',
    storageBucket: 'noticeboard-aebdd.firebasestorage.app',
    iosBundleId: 'com.example.norticeboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDKinsFG2n9tvuhL9MEsICXLXqSfnlJC8',
    appId: '1:1065290692027:ios:384cb508cbc5995e85409e',
    messagingSenderId: '1065290692027',
    projectId: 'noticeboard-aebdd',
    storageBucket: 'noticeboard-aebdd.firebasestorage.app',
    iosBundleId: 'com.example.norticeboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK3RSB_FjUAkd1iRkI1QxBNZdutBTZKsk',
    appId: '1:1065290692027:web:a8c59cd917002cab85409e',
    messagingSenderId: '1065290692027',
    projectId: 'noticeboard-aebdd',
    authDomain: 'noticeboard-aebdd.firebaseapp.com',
    storageBucket: 'noticeboard-aebdd.firebasestorage.app',
    measurementId: 'G-MRK9MGCVD9',
  );
}
